# Generated by Django 4.1.7 on 2023-03-28 16:25

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, max_length=5000)),
                ('nacimiento', models.DateTimeField(verbose_name='Fecha Nacimiento')),
                ('fk_nacionalidad', models.IntegerField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
