# Generated by Django 4.1.7 on 2023-03-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fk_nacionalidad',
            field=models.IntegerField(),
        ),
    ]
