# Generated by Django 4.1.7 on 2023-03-28 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_persona_fk_nacionalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.TextField(blank=True, max_length=5000)),
                ('nacionalidad', models.TextField(blank=True, max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fk_nacionalidad',
        ),
        migrations.CreateModel(
            name='PersonaPais',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, max_length=5000)),
                ('nacimiento', models.DateTimeField(verbose_name='Fecha Nacimiento')),
                ('nombre_pais', models.TextField(blank=True, max_length=5000)),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pais')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pais'),
            preserve_default=False,
        ),
    ]
