# Generated by Django 4.1.7 on 2023-03-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pais_remove_persona_fk_nacionalidad_personapais_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nacionalidad',
            new_name='nacionalidad_id',
        ),
        migrations.RenameField(
            model_name='personapais',
            old_name='nacionalidad',
            new_name='nacionalidad_id',
        ),
    ]
